//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int BookingId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime BookingDate { get; set; }
        public string SpecialOrder { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<int> VenueId { get; set; }
        public Nullable<int> FarmId { get; set; }
        public System.TimeSpan BookingTimeFrom { get; set; }
        public System.TimeSpan BookingTimeTo { get; set; }
    
        public virtual Farm Farm { get; set; }
        public virtual User User { get; set; }
        public virtual WeddingVenue WeddingVenue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
