//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterPieceEntities4 : DbContext
    {
        public MasterPieceEntities4()
            : base("name=MasterPieceEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookingCloth> BookingCloths { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<ClothDetail> ClothDetails { get; set; }
        public virtual DbSet<Cloth> Clothes { get; set; }
        public virtual DbSet<FarmDetail> FarmDetails { get; set; }
        public virtual DbSet<Farm> Farms { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<FoodDetail> FoodDetails { get; set; }
        public virtual DbSet<InvitationCardForm> InvitationCardForms { get; set; }
        public virtual DbSet<InvitationCard> InvitationCards { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<PhotographerDetail> PhotographerDetails { get; set; }
        public virtual DbSet<Photographer> Photographers { get; set; }
        public virtual DbSet<RegisteredService> RegisteredServices { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WeddingCart> WeddingCarts { get; set; }
        public virtual DbSet<WeddingVenueDetail> WeddingVenueDetails { get; set; }
        public virtual DbSet<WeddingVenue> WeddingVenues { get; set; }
    }
}
