//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingCloth
    {
        public int BookingClothId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime BookingDateFrom { get; set; }
        public System.DateTime BookingDateTo { get; set; }
        public string SpecialOrder { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public int ClothId { get; set; }
    
        public virtual Cloth Cloth { get; set; }
        public virtual User User { get; set; }
    }
}
