//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothDetail
    {
        public int ClothDetailId { get; set; }
        public int ClothId { get; set; }
        public string ImageUrl1 { get; set; }
        public string ImageUrl2 { get; set; }
        public string ImageUrl3 { get; set; }
        public string ImageUrl4 { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
        public string ClothMaterial { get; set; }
        public string Features { get; set; }
        public string PriceDetails { get; set; }
        public string Name { get; set; }
    
        public virtual Cloth Cloth { get; set; }
    }
}
