//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPiece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public int OrderId { get; set; }
        public string CardNumber { get; set; }
        public string CardOwnerName { get; set; }
        public string CVV { get; set; }
        public int ExpirationYear { get; set; }
        public int ExpirationMonth { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
